version: '3.12'

services:
  database-service:
    build:
      context: ..
      dockerfile: practice6/database_service.dockerfile
    container_name: database-service
    ports:
      - "8002:8002"
    environment:
      - INTERNAL_SERVICE_TOKEN=${INTERNAL_SERVICE_TOKEN}
    networks:
      - microservices-network

  business-service:
    build:
      context: ..
      dockerfile: practice6/business_service.dockerfile
    container_name: business-service
    ports:
      - "8001:8001"
    environment:
      - INTERNAL_SERVICE_TOKEN=${INTERNAL_SERVICE_TOKEN}
      - DATABASE_SERVICE_URL=http://database-service:8002
    depends_on:
      - database-service
    networks:
      - microservices-network

  client-service:
    build:
      context: ..
      dockerfile: practice6/client_service.dockerfile
    container_name: client-service
    ports:
      - "8000:8000"
    environment:
      - APP_TOKEN=${APP_TOKEN}
      - INTERNAL_SERVICE_TOKEN=${INTERNAL_SERVICE_TOKEN}
      - BUSINESS_SERVICE_URL=http://business-service:8001
      - DATABASE_SERVICE_URL=http://database-service:8002
    depends_on:
      - business-service
      - database-service
    networks:
      - microservices-network

  scheduler-service:
    build:
      context: ..
      dockerfile: practice6/scheduler_service.dockerfile
    container_name: scheduler-service
    ports:
      - "8003:8003"
    environment:
      - APP_TOKEN=${APP_TOKEN}
      - CLIENT_SERVICE_URL=http://client-service:8000
    depends_on:
      - client-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
